name: Build and Release Go Binaries

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Get previous release tag
        id: prev_tag
        run: |
          tag=$(gh release list --limit 1 --json tagName --jq '.[0].tagName' || echo "v0.0.0")
          echo "prev_tag=$tag" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Get latest commit message
        id: commit_msg
        run: |
          # 使用多行安全写入
          git log -1 --pretty=%B > commit_message.txt
          echo "commit_msg<<EOF" >> $GITHUB_ENV
          cat commit_message.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Calculate next version (semantic)
        id: next_tag
        shell: bash
        run: |
          # 安全读取多行环境变量
          msg="$(cat <<< "${{ env.commit_msg }}")"
          prev="${{ env.prev_tag }}"
          echo "Previous tag: $prev"
          echo "Commit message: $msg"

          # 初始版本号 v0.1.0
          if [[ "$prev" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
            major=${BASH_REMATCH[1]}
            minor=${BASH_REMATCH[2]}
            patch=${BASH_REMATCH[3]}
          else
            major=0
            minor=1
            patch=0
          fi

          # 语义化版本规则
          if [[ "$msg" == *"BREAKING CHANGE:"* ]]; then
            major=$((major+1))
            minor=0
            patch=0
          elif [[ "$msg" == feat:* ]]; then
            minor=$((minor+1))
            patch=0
          else
            patch=$((patch+1))
          fi

          next="v$major.$minor.$patch"
          echo "next_tag=$next" >> $GITHUB_ENV
          echo "Next tag: $next"

      - name: Generate release notes
        id: release_notes
        shell: bash
        run: |
          # commit range 从上一个 release 到 HEAD
          if [ "${{ env.prev_tag }}" = "v0.0.0" ]; then
            range=$(git rev-list --max-parents=0 HEAD)..HEAD
          else
            range=${{ env.prev_tag }}..HEAD
          fi
          echo "Commit range for notes: $range"

          notes=$(git log $range --pretty=format:'- %s (%an)')
          echo "release_notes<<EOF" >> $GITHUB_ENV
          echo "$notes" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Build binaries
        run: |
          mkdir -p dist
          GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -o dist/benchmarks-windows-amd64.exe main.go
          GOOS=linux   GOARCH=amd64 CGO_ENABLED=0 go build -o dist/benchmarks-linux-amd64 main.go
          GOOS=darwin  GOARCH=amd64 CGO_ENABLED=0 go build -o dist/benchmarks-darwin-amd64 main.go
          GOOS=darwin  GOARCH=arm64 CGO_ENABLED=0 go build -o dist/benchmarks-darwin-arm64 main.go

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.next_tag }}
          name: Release ${{ env.next_tag }}
          files: dist/*
          body: ${{ env.release_notes }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
